### ISSUE TITLE
why does bin/compile invoke bin/weigh?

### ISSUE THREAD

**Issue by tmornini** [devpunks/snuggsi#103]

**Comment by tmornini** [comment]
Why are there both bin/weigh and bin/validate-weight? bin/weigh only invokes bin/validate-weight. Worse yet, it throws away the exit status.

Why does bin/compile invoke bin/weigh? Appears to violate separation of concerns.

Why does watch/index.es invoke bin/validate-weight and why is ```|| true``` required? bin/validate-weight returns status code correctly, no need to embellish it, I think.

**Comment by snuggs** [comment]
@tmornini ll address your 1 and 2 in a PR. Seems like they are development related and can adjust watch script as such. Definitely want to validate after every time i weigh and didn't know another way besides `bin/weigh && bin/validate-weight` in my watch script. Perhaps that's what it should be.

1. Where else would `validate-weight` be called but after `bin/weigh`?
2.  because i was checking weight after deploy but think it's more a `test` situation. And truth be told I really don't look at it now that I have a weigh routine during development. Consider it the predecessor to your script but more details about other encoding versions.
3. is because > https://github.com/devpunks/snuggsi/pull/92#issuecomment-313950407

**Comment by tmornini** [comment]
@snuggs

> Where else would validate-weight be called but after bin/weigh?

bin/weigh *only* calls bin/validate-weight.

And, to make matters worse, it's not CATAT. bin/weigh doesn't weigh anything! 😄

**Comment by snuggs** [comment]
@tmornini confused... :thinking: My "weigh" was merely viewing byte information from an `ls` command. I didn't know about awk either so there was none of that. I just needed to see how many bytes each file weighed in `./dist` each time they changed. https://github.com/devpunks/snuggsi/blob/master/bin/weigh#L3

**Comment by tmornini** [comment]
@snuggs what about:

https://github.com/devpunks/snuggsi/blob/master/bin/weigh#L5

**Comment by snuggs** [comment]
ok let's fall back a little @tmornini 
>Why are there both bin/weigh and bin/validate-weight? bin/weigh only invokes bin/validate-weight. Worse yet, it throws away the exit status

I think you were going through it as you were typing as:
1. weigh doesn't ONLY call that. It never was there before I just put it there bcause it logically makes sense to check if there is an overweight validation AFTER weighing. Think 18 wheeler checkpoints at the highway. No difference. The validation happens on the scale.

2. if weight validation wasn't there then i'd have to kick the can down the road to somewhere else. I could put it in whatever calls weigh but that's TOO separated for our needs. 

Again I mentioned this few lines of script of yours should have went in `weigh` in the first place like it is now. Didn't think there was a need for 2 scripts but didn't think you knew what was going on with the scripts. Like the `package` script. it's there but i only use it one off because it duplicates much of what already is going on. Now validate weight is super handy but i feel not really bonafied to be it's own script.

2. Need to see weight. Was previously using eyeballs to validate. "Weigh isn't doing anything" that `ls` is all i needed for eyeball check before. Weigh is nice but having weigh and validate i feel is decoupling too much.  Would be like having a separate file for `ls` and another for `awk` when you just need both of them to work at the same time.
