### ISSUE TITLE
Lock down permissions

### ISSUE THREAD

**Issue by pachonk** [devpunks/snuggsi#120]
Would it make sense for us to lock down write access a bit more and allow contributions via forked PR?
I feel a little uneasy about the count of people with write access.

**Comment by snuggs** [comment]
What's to feel uneasy about? Who's burning down the house @pachonk?

**Comment by brandondees** [comment]
it is a pretty long list of folks now. that said i don't really want to force a change while there's no real trouble happening, at least until we have a nice guide written up for that whole workflow.

**Comment by snuggs** [comment]
Plus although may be uncomfortable protected branches allow the same functionality. You see the whole reason they were invented is BECAUSE it removes the need for people to have to fork. I spend real time cleaning up repos that i've contributed PRs to only because i had to fork because couldn't edit and submit a PR directly from Repo. Protected allows anyone to submit a PR but MUST get reviewed before merging. This lowers many barriers to new devs coming on trying to just edit the README.md /cc @cristhiandick

**Comment by snuggs** [comment]
@pachonk if this satisfies your concern we can close this issue. Trying to keep issue count within 1 page. ;-)

**Comment by pachonk** [comment]
Feel free to close. I just wanted to at least bring this up.
