### ISSUE TITLE
Preload Reusable Component `<links>`

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#151]
# Reusable Component `<link>`s

See github.com/whatwg/html/issues/2791#issuecomment-332403076
@brandondees 
could be on to something 
```html
<link rel=include href=path/to/include.html>
```
And what i love is no need for closing tag. Also there is support for multiple `rel=` attribute values. `rel="preload include"` Just might work as we'd expect!! 🎉 

Thoughts...

**Comment by brandondees** [comment]
yeah this is what i thought was being discussed the whole time, we were just looking at a custom element as a poor man's alternative to attempt to demonstrate popular interest

**Comment by snuggs** [comment]
@brandondees how does this declaration feel?

```html
<link id=foo-bar rel=preload href=/foo-bar.html>
```

We are basically abiding by the preloading spec and using convention of `id=component-name` as the link to custom elements of same tag name.
```html
<!-- LATER IN MARKUP -->
<foo-bar></foo-bar>
```
I do realize this is a slippery slope between `include` and `import` _(should we even be calling it that anymore?)_

Just looking for a convention stat because need this sooner than later.

The bad side is `rel=include` isn't passing HTML parser validation (w3c so could also #FakeCare)
The good side is our `id=` convention passes. 

I kinda like having a `preload` where available out of the box #BatteriesAlmostIncluded
![capture d ecran 2017-09-28 a 17 16 43](https://user-images.githubusercontent.com/38223/30996031-8c127faa-a472-11e7-9f39-ae355eef1dbb.png)

**Comment by brandondees** [comment]
couple things:

what if i use `<link id=baz-qux rel=preload href=/foo-bar.html>` where foo-bar is the element defined in the include? do i get to alias the vendor's foo-bar element to my own name? 

what if the include defines multiple custom elements? do i need to specify which to import into the parent document's namespace by using the id attribute?

how does `preload` get us what we want, exactly? does the spec make that available to the parent document's ES context for programmatic access?

any idea what we can rely on with future html modules? can it be polyfilled? given that imports have been declared dead by various parties, that seems to be what we are meant to be planning around, but i haven't seen any indication that it's in any way predictable yet. suppose whatever we decide to do involves designing our own non-standard interface which can wrap either the future standard implementation without breaking expectations, or just hack together something that fakes enough of the expected behavior to serve our purposes in the meantime, without relying on the specs being hammered out?

**Comment by snuggs** [comment]
@brandondees *yes*

**Comment by tmornini** [comment]
@brandondees @snuggs K.I.S.S. 😄

If you want to "worry" about element names (which I'm not sure you should), prepend the include's ID to the included's ID...

**Comment by brandondees** [comment]
@tmornini for me, the semantics always matter, but for this, there could easily be namespacing issues to work around as well. prepending id might be sufficient for that, though, although in my ideal version I think I'd want the `name` attr to specify what the new element should be called in the parent document.

**Comment by tmornini** [comment]
@brandondees What if there are multiple elements in the include? 😄

**Comment by brandondees** [comment]
@tmornini snuggsi is convention over configuration, with the convention being one component per import, but presumably we can use some JS to re-map those manually if needed.

**Comment by snuggs** [comment]
True!!! @brandondees @tmornini also `name` isn't a valid attr for `<link>` elements. I've been working on this and arrived at the following convention. Will do a PR with documentation. https://github.com/devpunks/snuggsi/blob/master/index.html#L19-L29

This allows us to get HTML "include"s without even using Javascript _(In "User Land")_

Works SWEET TOO!!! We also get preloaded asynchronous non-blocking, *HIGH PRIORITY* download threads so when we "stamp" the custom elements with the template from the remote file it takes no time to respond from cache and works without even defining a custom element.

```html
<link id=foo-bar rel=preload href=foo.html>
<!--
  Any dependencies in foo.html
  (i.e. <script> or <style> or <link type=stylesheet>)
  will be injected here after call site.
-->

<foo-bar><!-- contents from <template> in foo.html will be stamped here --></foo-bar>
<foo-bar>
  <!-- can still replace slots within foo.html without defining a custom element in javascript !!! -->
  <h1 slot=header>Slot replacement</h1>
</foo-bar>

<foo-bar><!-- multiple elements work too--></foo-bar>
```

**Comment by snuggs** [comment]
@brandondees @tmornini was kinda leaning towards the following hint.
```html
<meta name=foo-bar content=foo-bar.html>
```
But following caveats have to be overcome:
  1. `<meta>` tags aren't allowed in `<body>` and links are _(New with HTML5)_
  2. We don't get the free resource fetching from greenfield browsers as we do with `<link rel=preload>`

But i like it better because it's more terse than:
```html
<link
  as=foo-bar
  id=foo-bar
  rel=preload
  href=foo-bar.html>
```

**Comment by snuggs** [comment]
@brandondees @btakita @rianby64 @janz93 @kurtcagle  #ping ☝️

**Comment by brandondees** [comment]
prerender is not appropriate for this type of thing, as it would render the remote document as if it is going to be the next full page navigation, for instant visual update on click. including a component in a parent doc wouldn't meet the browser's expectations and might achieve wasted resources with no user facing benefit. it happens at the browser's discretion, and in lowest priority mode (only when resources are idle, and the cached result might only be kept in memory for a short period, maybe up to a few minutes). it's intended specifically for situations where the user's workflow after loading the current page is very likely to be to immediately perform a subsequent navigation action and that next page can be predicted. the main intended use case for this is clicking through paginated content at a rapid pace, or pages that have a very clear funnel progression such as e.g. "home -> pricing -> contact us". preload is much more generally applicable as it is more about pre-caching the content to front-load the network activity without performing the rendering work eagerly. I believe the user agent still keeps this cache short-lived by default but because it's not using the CPU/GPU resources as aggressively it's likely to be tuned to be more general purpose. when both are combined in an optimal way, i believe the end result should be something approximating the UX of turbolinks. instant page transitions for the most likely navigation path, and very snappy transitions for the site overall due to pre-cached external content. in both cases, it's important to remember that these are "hints" not directives, the user agent is in control of the process and behavior may vary based on circumstances, so these are not dependable in any sense.

as for the usage API, i am not picky as long as it's not surprising/unintuitive, and as long as we allow for developer control where appropriate when we are applying convention over configuration defaults.

**Comment by snuggs** [comment]
@brandondees so the "proposal" is reasonable as far as developer ergonomics? What I love is that even if someone "divorces" the snuggsi library they still are in far better shape than they were before they picked up the library as far as the platform is concerned.

**Comment by snuggs** [comment]
@brandondees @halorium @albertoponti @cristhiandick @tmornini @btakita @scottmacdowell @rianby64  addressed and documented. https://github.com/devpunks/snuggsi#remote-components
