### ISSUE TITLE
Should we use brotli package?

### ISSUE THREAD

**Issue by snuggs** [devpunks/snuggsi#30]
Would this prevent the need to install?

@brandondees 

https://www.npmjs.com/package/brotli
https://github.com/devpunks/snuggsi/blob/master/package.json#L46

**Comment by brandondees** [comment]
seems like it'll work as long as you're not using it for dynamic compression.

**Comment by brandondees** [comment]
have you started using zopfli also yet?

**Comment by snuggs** [comment]
Nope heard about it. Perhaps an integration step? I like the options. @tmornini any input on zopfli? @brandondees he rocks with brotli. 💪 

Here's where we currently stand. /cc @mrbernnz @btakita 
https://github.com/devpunks/snuggsi/tree/master/dist#readme

**Comment by brandondees** [comment]
brotli is the better compression, and it works both dynamic and static with the appropriate server configs. zopfli is gzip-compatible but takes a long time to process, so it's only useful for static pre-compression, but if you can integrate it into the build it's free compression improvement for clients that take gzip but not brotli. that said, brotli's going mainstream with all the evergreen browsers (edge is getting it soon IIRC) so it may not be a huge deal.

**Comment by tmornini** [comment]
@snuggs I'm not sure what we're talking about. :-)

If we're talking about how to distribute it, the choices are:

  1) choose the best one and stick with it. I see evidence brotli may be that choice.
  2) choose #1 and the 1 or 2 common alternatives. This makes everything more confusing.
  3) choose 1 & 2 and add more, ad nauseum. This makes everything far more confusing.

**Comment by brandondees** [comment]
It's standard practice, although not necessarily default out-of-the-box configuration, to enable dynamic deflate and gzip compression for web servers. There's also always the option of providing the server with pre-compressed static assets from build-time to use and avoid the dynamic computational overhead at request time. The HTTP Accept-Encoding header enables best-effort preference-based auto negotiation between client and server. Deflate is pretty universally supported, and gzip is pretty universal now as well. Zopfli is a more aggressive / improved gzip that is backwards compatible, so if you are going to pre-compress static assets at build time, if you don't care about build speed you can get some free compression gains over traditional gzip. Because it's slow, it's not a practical option for dynamic compression. Brotli is the next evolution but is not backwards compatible, so both client and server must support it and be configured to prefer it. It's more effective compression than gzip, and it's fast, so it works for either dynamic or static approaches. Chrome and Firefox already prefer it, and Edge support is around the corner if my information is correct. I'm not sure about the other browsers, but regardless it's not 100% universal yet, so you wouldn't want to use brotli exclusively with no fallback option, unless you want to treat the 'lesser' browsers as second-class and not compress for them. The ideal for end user performance is to ship pre-compressed files in brotli, zopfli, and uncompressed. The next best thing is to enable dynamic brotli / gzip / deflate compression at the server level, which should happen anyway to handle non-static responses. The not best thing is to not bother, and let the users incur the bandwidth overhead based on whatever the default configurations are for the server of choice. For web pages which are already very small and fast to render, the marginal gains may not justify putting any explicit effort in, but for a library, every performance advantage is multiplied over the entire userbase, so IMHO it's wrong not to make every effort to ship the optimal result. We wouldn't be talking about it if jQuery and React were already small and light enough to not bother anyone.

**Comment by snuggs** [comment]
@mrbernnz we were just talking about this. As @tmornini taught me it's the mime type that is more important. File extensions are just side effects. In a sense the browser is telling us what it supports from what I gather. By allowing these options stats are saying orders of magnitude in savings for network latency.

https://en.wikipedia.org/wiki/Content_negotiation

Great video explaining how server authors should move forward. Content Negotiation is back and here to stay. 
https://www.youtube.com/watch?v=BPcjN_1qsdA

They say focus on Zopfli -> Brotli -> GZip -> uncompressed in that order.

**Comment by snuggs** [comment]
@tmornini this is what happens when we pick one and the browser doesn't support it. Get these weird funky characters because cannot decode. Seems `Vary` and `Accept-Encoding` are important. https://www.fastly.com/blog/best-practices-for-using-the-vary-header/

**Comment by snuggs** [comment]
@brandondees @tmornini will be using http2server for the time being. @mrbernnz and I discovered it watching the video above. So far it's "Batteries Included 🔋 " as it even automates the certificate process for us. Was pretty impressed at the feature set. Sounds like everyone's concerns are covered in this tool.

To be clear the end goal of the "why" is to
  1. get a better understanding of HTTP/2 server push
  2. Would like to host components (e.g. `//snugsi.es/header-group`, etc)
  3. Get a better understanding of compression as I never had to care about this before however extremely important to know from server side & client side in 2017.

https://gitlab.com/sebdeckers/http2server

**Comment by brandondees** [comment]
looks great. https://caddyserver.com/ may also be worth comparing. I think Caddy may be more feature-rich, but I haven't kept close track of how the http/2 stuff works.

**Comment by snuggs** [comment]
@tmornini @brandondees one thing i noticed is brotli is idempotent. Every time the gzip compressor gets run it creates a distinctly new file even with no diffs to the source. Our brotli compressor never diffs. 

How does one use this to advantage when serving?

1. it's fast.
2. it's idempotent (my favorite part)

Thanks for the caddyserver link will check it out.

**Comment by snuggs** [comment]
OH https://caddyserver.com server is written in GO @tmornini noice!.

**Comment by brandondees** [comment]
Hmm, I wonder if there is changing file metadata that goes into gzip that brotli ignores. Otherwise, the only other explanation I can think of is that the encoding process itself generates some metadata at runtime, perhaps. If it's just non-deterministic encoding that seems kinda silly.

**Comment by snuggs** [comment]
Yup. Also @brandondees seems nice https://twitter.com/jeresig/status/821768122017398785

@tmornini what's this HSTS and why 2 years and why does the rating go from A to A+? Forgive me but you know this context is my insecure zone. https://twitter.com/returnnull/status/821809973688750080

**Comment by snuggs** [comment]
Related #34

**Comment by tmornini** [comment]
@snuggs I'd recommend hosting this on S3 + CloudFront.

Zero need for a a server, hopefully tons of need for fast, low-latency file delivery. 😄

**Comment by brandondees** [comment]
yeah CDN is probably the way to go. bear in mind S3 itself is not a CDN

**Comment by tmornini** [comment]
Bear in mind I said S3 + CloudFront -- which can also do domain names and SSL...

**Comment by snuggs** [comment]
Oh that's great! Where would the content negotiation side be handled?

i.e. nginx brotli for picking up `Content-Encoding` @brandondees @tmornini

**Comment by brandondees** [comment]
AFAIK it's just apache/nginx level configuration. Or if you have something in front of that responding with static content, it's up to that layer. I'm wagering that any decent CDN will already be doing the right thing if you supply the files, but you may want to read up on that before choosing one.

**Comment by cristhiandick** [comment]
Is it possible to get a header of the objective discussion is getting bogged down on service providers. I believe Tom already solved the issue but my fault I still don't understand if you intent is to encourage a path to hold assets on s3 + cloudfront or you     aiming to provide a service?




Regards,
Cristhian

**Comment by tmornini** [comment]
@cristhian We're trying to figure out what the standard, default, compression method should be used to deliver the library, and how to arrange for that, and other formats as well.

**Comment by snuggs** [comment]
@RobertChristopher found a koa static server that is LESS THAN 200LOC (which i can probably get to 70). Satisfies Brotli and gzip. This is a temp solution of course but for now is more than enough. We run Koa and http2server is the lamborghini. However we just need a skateboard. Thoughts? If so i'll do a PR and we can implement immediately.

https://github.com/koajs/send

**Comment by RobertChristopher** [comment]
@snuggs Is it necessary to proxy http2server to koa? http2server includes a static file server implementation and support for Brotli compression.

**Comment by snuggs** [comment]
no we're not using http2server to start out @RobertChristopher however am VERY interested in it and is a fantastic golang project. For now a few dozen LOC should do the trick. Truth be told should probably be in `nginx.conf` file. Point is there are options.
