### ISSUE TITLE
Remove static keyword from the event handler

### ISSUE THREAD

**Issue by janz93** [devpunks/snuggsi#45]
```javascript
(class extends HTMLElement {
  
  static onclick () // "automagic" event registration
    { alert (this.textContent) }
})
```
 to be only
```javascript
(class extends HTMLElement {
  
  onclick () // "automagic" event registration
    { alert (this.textContent) }
})
```

**Comment by snuggs** [comment]
Hmmm @janz93 i REALLY like this. Much better. But the `static` keyword just screams out to me "Event Handler". Now that's a convention we control. Perhaps just my insecurity in using it the past few months. Because one thing @RobertChristopher mentioned (and @tmornini in the past) is don't mess with [Occam's Razor](https://en.wikipedia.org/wiki/Occam%27s_razor). Having `this` be the current instance of the custom element within a `static` method felt a really smelly to me. Basically the convention we are changing is: 
  1. If property is named one of the `GlobalEventHandler.on*` events then consider it an event handler. (Which we do already).
  2. the developer has to know the difference between an event handler and a regular helper method by the prefix `on`. 
  3. In the case of an explicit registration to an exotic handler `<foo-bar onclick=onbaz>` then they can theoretically have the same convention. However, since `onbaz` is not one of the W3C `on*` event handlers they could similarly use `<foo-bar onclick=whatever_as_long_as_defined_on_class>`.

Hope this makes sense. if so then we can move forward with this one.

/cc @brandondees @RobertChristopher @robcole @scottmacdowell @btakita @VicenteRD @mrbernnz @tmornini

**Comment by janz93** [comment]
I would consider something with `onbaz` an anti-pattern.
According to the JS style guides, multiple words should be written in [camel case](http://javascript.crockford.com/code.html#function)
Therefore I might consider throwing an error if you use something which isn't a defined [global event handler](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers)
I would rather have something like the following
```
onclick() {
  this.bar();
}

bar() {
  alert('bar');
}
```

**Comment by snuggs** [comment]
@janz93 awesome! I think what we are discussing is will `<foo-bar onclick=bar>` be explicit enough. Sounds like it will. The camelCase thing is a convention i don't really abide by, HOWEVER, if you recall the intent is to not impose any styling onto the component author. Which sounds like we are doing.

That said might want to read up on "classic event registration" which was the first way to register events onto DOM elements. This is pretty much what we are automating.
_(See code comments here)_ ➡️  https://github.com/devpunks/snuggsi/blob/master/elements/global-event-handlers.es#L3-L24
### Classic Event Registration Links

https://en.wikipedia.org/wiki/DOM_events#Traditional_model

https://www.quirksmode.org/js/events_tradmod.html

Please advise.

(To be clear i'm 100% with you. Let's remove the `static`)

**Comment by snuggs** [comment]
@lukemelia you and I were discussing these handlers while pairing. We used to use `static` as a hint to event handlers. But that was confusing from an ECMAScript perspective.
