### ISSUE TITLE
Docker help

### ISSUE THREAD

**Issue by janz93** [devpunks/snuggsi#52]
Hello, tom @snuggs referenced me to you.
I am currently in the process of learning docker.
In a current project, I work on I have docker-compose file.
Inside I have set the MySQL root_password as an Environment variable.
Of course this way I can't check in the docker-compose file into git.
So now I am wondering what is the best way to secrets with docker.
I read and found [Heroku is using an env. file](https://devcenter.heroku.com/articles/local-development-with-docker-compose) 
Others use the docker secret method which as far I understood works only in a swarm.
So I am confused and looking for someone to shed some light on that.
Thanks in advance

**Comment by snuggs** [comment]
@tmornini ping.

**Comment by brandondees** [comment]
related to this topic, i got into a thread with someone about the general concept of secrets as ENV vars, and the recommendation was strongly to avoid storing them on disk at all, and instead manage issuance from a centralized configuration management tool such as chef, salt, ansible, etc. all provide. kind of a heavy duty solution depending on what scale you're building at (certainly will add a lot of complexity to our typical client's infrastructure) but it does make sense security-wise and there are a big pile of other benefits to adopting those kinds of practices, so maybe it's worth it.

**Comment by tmornini** [comment]
@janz93 @brandondees I believe there is little difference between providing credentials as ENV vars and providing them via a secret management service.

At some point, the values must be read. If the code can get them, they can be stolen...

I'm 100% behind the idea that no credentials should be checked into source code. Some times you need secure items checked into source. In those cases, encrypt them and store the encryption keys wherever you store your credentials, decrypt the files, use them, and destroy them when you're finished with them. TLS certificates could be a good example here, though ACME makes that less necessary than in the past.

As with all things it's the nuances that matter.

In my most recent system, we provide credentials to applications running in docker containers via env vars.

Why?

Because we've very carefully managed those credentials' secrecy via our CI system, which allows encrypted env vars available only to the build process, have strict control over access to the containers, and most importantly, have docker containers that have only two files: a go executable binary and an HTTPS/TLS root certificate file. Finally, there's strict firewall rules that only allow port 80 and 443 access to a load balancer from the outside world, which is to say there's no way to access the system from the outside world.

At the end of the day, you really need to understand the attack vectors that would expose the credentials.

Even if you run your own datacenter you'd need to trust your HSM vendor to store the credentials securely.

Hope that helps!

**Comment by brandondees** [comment]
yes, somewhat @tmornini but i think the original question is more about _how_ to get ENV vars into the containers without writing them into the compose file, practically speaking.

**Comment by tmornini** [comment]
@brandondees Ah, sorry for missing the bullseye. :-)

I use compose files purely locally. Whatever it is that you're using for deployment will have a mechanism to inject the env vars.

For example, I use the AWS ECS task definition to define the environment vars to be set when starting a container.

janz93 said:

> Inside I have set the MySQL root_password as an Environment variable

As documented [here](https://docs.docker.com/compose/compose-file/#environment), docker-compose allows you to specify a null/nil value for an environment variable to indicate you wish to pass the value of the environment variable in the current shell down to the container.

So, remove the value -- but not environment variable -- from the from the docker-compose.yaml, and set the environment variable in the shell you're issuing the docker-compose commands from.

**Comment by brandondees** [comment]
very helpful / actionable, thanks @tmornini

**Comment by tmornini** [comment]
You're welcome, @brandondees.

**Comment by janz93** [comment]
Thank you @tmornini and @brandondees for the expertise on that matter.
I will look into the different solutions and will let you know what I ended up doing.
@snuggs Thanks for the connecting. As always much appreciated
