### ISSUE TITLE
Multiple templates of the same name issue

### ISSUE THREAD

**Issue by albertoponti** [devpunks/snuggsi#55]
@snuggs .. I found this issue when using the same name on multiple templates it does not render and it does not let you select the right exchange in the case below ..
  
```html
<template name=exchange>
  <option>{foo}
</template>
....
Then later
<template name=exchange>
  <option>{foo}
</template>
```

**Comment by snuggs** [comment]
Question... we currently support duplicate **tokens**:
The following feature is currently supported within the codebase:
```
<foo-bar>
  {baz} and another {baz}
</foo-bar>
```

However the following (bug/feature) use-case is not supported...yet:
```html
<header>Pizza Toppings</header>

<select name=topping1>
<template name=toppings>
  <option>{name}
</template>
</select>

<select name=topping2>
<template name=toppings>
  <option>{foo}
</template>
</select>
```
 SInce we use `querySelector` API instead of `querySelectorAll` only the first `<template>` is rendered. Should we allow duplicates like `{token}`s?

Please advise. And thanks in advance! <3

@btakita @brandondees @janz93 @mrbernnz @RobertChristopher @albertoponti @robcole @scottmacdowell

**Comment by brandondees** [comment]
i've always thought of `<template>` as a declaration of a reusable named fragment, not as a slot to be filled inline. snuggsi convention just happens to be to plug it in as such inline for single usage, which I suspect leads to this kind of confusion. we have `{token}` and `<slot>` for inserting content into templates, and `<template>` itself can also be declared separately rather than inline.

@albertoponti what's your intended outcome for this example code? you want the same content to be rendered in two places? or you want the same content structure to be used to render two different pieces of content?

@snuggs what's your idea for using a `<template>` declared in one place to be re-used for filling multiple token/slot positions elsewhere? does name bind to a distinct custom element that can be used passing new data in, or does it bind to a data property like we're used to seeing in e.g. angular?

**Comment by brandondees** [comment]
the notion of supporting the duplicates brings up other questions such as which template wins in the event that they are distinct from each other, and does that lead to other problems? if they aren't expected/allowed to be distinct, doesn't it violate DRY to be pasting the same exact template structure into multiple places? if they can be distinct, does the last one overwrite the others? or do they each get replaced separately per usage? that also brings up DRY concerns in the event that you want to have similarity in some and distinct form for others. all in all it doesn't sound like the right type of usage for this element when we have other tools that can get the job done more unambiguously, IMHO. it calls into question the practice of inlining the template definition in the first place though, given the expectations it seems to set.

**Comment by albertoponti** [comment]
@brandondees .. I understand the issue now from a different angle .. my intended outcome is to get prices from different exchanges, so the list of exchanges is not really duplicate, it is just a list from where I can go and choose .. by choosing this or that exchange in two places will determine where I go and get the pricing information .. that will be different from exchange to exchange .. hope it was clear enough

**Comment by brandondees** [comment]
ok so you're mapping to a list of exchanges in each location, which is suggestive of its own custom element / template. i think it probably makes sense to go ahead and extract that to `<exchange-list>` or whatever and just plug that in where it's needed.

**Comment by albertoponti** [comment]
@brandondees thanks .. makes sense .. so my decision tree would be to select the exchange and then the security which is the second list that I need to choose from .. which can be ```<security-list>``` ... and get my final result displayed ..

**Comment by brandondees** [comment]
yeah for me basically any time i am re-using some fragment of code that will need to be updated in both (or more) places for the same reason in the future, that's true duplication and can generally be extracted out to its own unit somehow. in this case you're creating additional small components that you can plug in rather than duplicating inline <template> usage for the same purpose. if i've understood correctly

**Comment by albertoponti** [comment]
.. @brandondees yes you understood correctly and thanks for your comments really clarified the issue .. @snuggs

**Comment by snuggs** [comment]
Interesting. Will have to try this out. May be able to punt on this feature @brandondees.  /cc @albertoponti. I guess now is the time to see how nested components work. :-)

**Comment by snuggs** [comment]
I think we are clear here @brandondees @albertoponti let's punt on rendering multiple templates of the same name. as Dees said can mitigate by creating a "sub component" and using it multiple times.
