### ISSUE TITLE
"1 1500 Ethernet Frame"

### ISSUE THREAD

**Issue by pachonk** [devpunks/snuggsi#90]
It should be noted that note that most switches default is exactly 1500, so it probably takes 2 packets to download. That said, it's still pretty small.

**Comment by snuggs** [comment]
@pachonk 1.24kB

![capture d ecran 2017-07-06 a 12 41 25](https://user-images.githubusercontent.com/38223/27922270-7a667188-6248-11e7-9a58-3eff6c667726.png)

**Comment by tmornini** [comment]
👍

**Comment by pachonk** [comment]
I might need to wireshark this just to verify. Can close this for now if you'd like.

**Comment by pachonk** [comment]
Dang! I don't have a hub so I either gotta order one or program one of my switched -.-

**Comment by tmornini** [comment]
I don't think the aim here is whether or not it's **actually* delivered in a single frame, but whether or not it **could be** delivered in a single frame.

It's **clearly** within a standard ethernet frame as 1.24 kB < 1.5 kB [Ethernet v2 maximum payload size of 1500 octets](https://en.wikipedia.org/wiki/Ethernet_frame#Ethernet_II).

If you'd like to keep this open for a while until you look into it, that's fine.

Otherwise, yes, please do close this if the above reasoning seems reasonable. 😄

**Comment by pachonk** [comment]
Yeah, I didn't look at the real size. This should be closed.

**Comment by pachonk** [comment]
I probably will test to see how many packets the actual data comes through if I get some real free time.

**Comment by tmornini** [comment]
@pachonk 👍
